# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwin.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Init_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Init_Button.setGeometry(QtCore.QRect(10, 10, 611, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.Init_Button.setFont(font)
        self.Init_Button.setObjectName("Init_Button")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Move_X_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Move_X_Button.setGeometry(QtCore.QRect(210, 70, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.Move_X_Button.setFont(font)
        self.Move_X_Button.setObjectName("Move_X_Button")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.Move_Y_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Move_Y_Button.setGeometry(QtCore.QRect(210, 120, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.Move_Y_Button.setFont(font)
        self.Move_Y_Button.setObjectName("Move_Y_Button")
        self.X_distance = QtWidgets.QLineEdit(self.centralwidget)
        self.X_distance.setGeometry(QtCore.QRect(50, 70, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.X_distance.setFont(font)
        self.X_distance.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.X_distance.setObjectName("X_distance")
        self.Y_distance = QtWidgets.QLineEdit(self.centralwidget)
        self.Y_distance.setGeometry(QtCore.QRect(50, 120, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.Y_distance.setFont(font)
        self.Y_distance.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Y_distance.setObjectName("Y_distance")
        self.Scan_Table = QtWidgets.QTableWidget(self.centralwidget)
        self.Scan_Table.setGeometry(QtCore.QRect(10, 190, 301, 201))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.Scan_Table.setFont(font)
        self.Scan_Table.setTextElideMode(QtCore.Qt.ElideRight)
        self.Scan_Table.setShowGrid(True)
        self.Scan_Table.setGridStyle(QtCore.Qt.SolidLine)
        self.Scan_Table.setCornerButtonEnabled(True)
        self.Scan_Table.setObjectName("Scan_Table")
        self.Scan_Table.setColumnCount(1)
        self.Scan_Table.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.Scan_Table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Scan_Table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Scan_Table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Scan_Table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Scan_Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Scan_Table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Scan_Table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Scan_Table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Scan_Table.setItem(3, 0, item)
        self.Scan_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Scan_Button.setGeometry(QtCore.QRect(10, 400, 301, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Scan_Button.setFont(font)
        self.Scan_Button.setObjectName("Scan_Button")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(320, 410, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.Open_SPC_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Open_SPC_Button.setGeometry(QtCore.QRect(320, 40, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.Open_SPC_Button.setFont(font)
        self.Open_SPC_Button.setObjectName("Open_SPC_Button")
        self.Scan_Table_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.Scan_Table_2.setGeometry(QtCore.QRect(320, 90, 301, 251))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.Scan_Table_2.setFont(font)
        self.Scan_Table_2.setTextElideMode(QtCore.Qt.ElideRight)
        self.Scan_Table_2.setShowGrid(True)
        self.Scan_Table_2.setGridStyle(QtCore.Qt.SolidLine)
        self.Scan_Table_2.setCornerButtonEnabled(True)
        self.Scan_Table_2.setObjectName("Scan_Table_2")
        self.Scan_Table_2.setColumnCount(1)
        self.Scan_Table_2.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.Scan_Table_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Scan_Table_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Scan_Table_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Scan_Table_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Scan_Table_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Scan_Table_2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Scan_Table_2.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.Scan_Table_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Scan_Table_2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Scan_Table_2.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Scan_Table_2.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Scan_Table_2.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Scan_Table_2.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Scan_Table_2.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Scan_Table_2.setItem(6, 0, item)
        self.Convert_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Convert_Button.setGeometry(QtCore.QRect(320, 350, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.Convert_Button.setFont(font)
        self.Convert_Button.setObjectName("Convert_Button")
        self.Location = QtWidgets.QLabel(self.centralwidget)
        self.Location.setGeometry(QtCore.QRect(10, 30, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.Location.setFont(font)
        self.Location.setObjectName("Location")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 170, 301, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Init_Button.setText(_translate("MainWindow", "Init/Reset"))
        self.label_2.setText(_translate("MainWindow", "X"))
        self.Move_X_Button.setText(_translate("MainWindow", "Move"))
        self.label_3.setText(_translate("MainWindow", "Y"))
        self.Move_Y_Button.setText(_translate("MainWindow", "Move"))
        self.X_distance.setText(_translate("MainWindow", "+5000"))
        self.Y_distance.setText(_translate("MainWindow", "-5000"))
        item = self.Scan_Table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Width"))
        item = self.Scan_Table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Height"))
        item = self.Scan_Table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Delay"))
        item = self.Scan_Table.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Grid_Size"))
        item = self.Scan_Table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.Scan_Table.isSortingEnabled()
        self.Scan_Table.setSortingEnabled(False)
        item = self.Scan_Table.item(0, 0)
        item.setText(_translate("MainWindow", "100"))
        item = self.Scan_Table.item(1, 0)
        item.setText(_translate("MainWindow", "100"))
        item = self.Scan_Table.item(2, 0)
        item.setText(_translate("MainWindow", "1"))
        item = self.Scan_Table.item(3, 0)
        item.setText(_translate("MainWindow", "10"))
        self.Scan_Table.setSortingEnabled(__sortingEnabled)
        self.Scan_Button.setText(_translate("MainWindow", "Start Scan"))
        self.Open_SPC_Button.setText(_translate("MainWindow", "Open SPC"))
        item = self.Scan_Table_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Width"))
        item = self.Scan_Table_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Height"))
        item = self.Scan_Table_2.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Start_data"))
        item = self.Scan_Table_2.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Grid_Size"))
        item = self.Scan_Table_2.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Start_Freq"))
        item = self.Scan_Table_2.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "End_Freq"))
        item = self.Scan_Table_2.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Freq_step"))
        item = self.Scan_Table_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.Scan_Table_2.isSortingEnabled()
        self.Scan_Table_2.setSortingEnabled(False)
        item = self.Scan_Table_2.item(0, 0)
        item.setText(_translate("MainWindow", "100"))
        item = self.Scan_Table_2.item(1, 0)
        item.setText(_translate("MainWindow", "100"))
        item = self.Scan_Table_2.item(2, 0)
        item.setText(_translate("MainWindow", "10"))
        item = self.Scan_Table_2.item(3, 0)
        item.setText(_translate("MainWindow", "10"))
        item = self.Scan_Table_2.item(4, 0)
        item.setText(_translate("MainWindow", "520"))
        item = self.Scan_Table_2.item(5, 0)
        item.setText(_translate("MainWindow", "540"))
        item = self.Scan_Table_2.item(6, 0)
        item.setText(_translate("MainWindow", "1"))
        self.Scan_Table_2.setSortingEnabled(__sortingEnabled)
        self.Convert_Button.setText(_translate("MainWindow", "Convert"))
        self.Location.setText(_translate("MainWindow", "Alignment"))

